RunnerConfiguration:
  jobRegistryAPIClient:
    $type: org.codingmatters.poom.client.PoomjobsJobRegistryAPIClient
  runnerRegistryAPIClient:
    $type: org.codingmatters.poom.client.PoomjobsRunnerRegistryAPIClient
  jobWorker:
    $type: java.util.concurrent.ExecutorService
  callbackBaseUrl: string
  ttl: long
  jobCategory: string
  jobName: string
  processorFactory:
    $type: org.codingmatters.poom.runner.JobProcessor.Factory