RunnerConfiguration:
  jobRegistryAPIClient:
    $type: org.codingmatters.poomjobs.client.PoomjobsJobRegistryAPIClient
  runnerRegistryAPIClient:
    $type: org.codingmatters.poomjobs.client.PoomjobsRunnerRegistryAPIClient
  jobWorker:
    $type: java.util.concurrent.ExecutorService
  callbackBaseUrl: string
  ttl: long
  jobCategory: string
  jobName:
    $list: string
  processorFactory:
    $type: org.codingmatters.poom.runner.JobProcessor.Factory
  jobRegistryUrl: string
  endpointHost: string
  endpointPort: int
  healthCheckProcessor:
    $type: org.codingmatters.rest.api.Processor