#%RAML 1.0
title: Poomjobs Runner API
version: v1
baseUri: https://api.codingmatters.org/poomjobs
mediaType: application/json

types:
  !include poomjobs-types.raml

/jobs/running/{jobId}:
  displayName: Running Job
  uriParameters:
    jobId:
      type: string
      required: true
  put:
    body: Job
    responses:
      201:
        description: runner accepts running the job and redirect to its URL
        headers:
          Location: string
      409:
        description: runner is busy, it cannot accept running the job (RUNNER_IS_BUSY)
        body: Error
  /failure/termination:
    displayName: aborted job termination
    description: This endpoint is used to notify a runner that a job as been aborted from another runner. Some callback may not be called.
    post:
      body: Job
      responses:
        204:
          description: job termination success
        500:
          description: error processing job proper termination
          body: Error
