#%RAML 1.0
title: Poomjobs Job Registry API
version: v1
baseUri: https://api.codingmatters.org/poomjobs
mediaType: application/json

types:
  !include poomjobs-types.raml

/jobs:
    displayName: JobCollection
    get:
        queryParameters:
            range: string

            name: string
            category: string
            runStatus: string
            exitStatus: string
        responses:
            200:
                description: complete list of jobs or last elements of the list of jobs
                headers:
                    Content-Range: string
                    Accept-Range: string
                body: Job[]
            206:
                description: complete list of jobs or last elements of the list of jobs
                headers:
                    Content-Range: string
                    Accept-Range: string
                body: Job[]
            416:
                description: the specified range is not acceptable. Error code is ILLEGAL_RANGE_SPEC.
                headers:
                    Content-Range: string
                    Accept-Range: string
                body: Error
            500:
                description: UNEXPECTED_ERROR.
                body: Error
    post:
        headers:
            account-id: string
        body: JobCreationData
        description: |
          A job is created from the minimal information provided with
          the payload JobCreationData.
          * The created job will have it's submission date setted.
          * The job accounting information will be initialized given the account-id header.
          * The job will have its run status setted to PENDING.
        responses:
            201:
                description: new job created
                headers:
                    Location: string
            400:
                description: request is not acceptable. Code ILLEGAL_JOB_SPEC.
                body: Error
            500:
                description: UNEXPECTED_ERROR.
                body: Error
    /{jobId}:
        displayName: JobResource
        uriParameters:
            jobId:
                type: string
                required: true
        get:
            description: |
                If a job with the given jobId, returns the full description of the job.
            responses:
                200:
                    description: a job with the given jobId is found and returned
                    body: Job
                404:
                    description: no job found with the given jobId. Code JOB_NOT_FOUND.
                    body: Error
                500:
                    description: UNEXPECTED_ERROR.
                    body: Error
        patch:
            body: JobUpdateData
            headers:
                account-id: string
                current-version: string
            description: |
                The job with the given jobId is updated provided the payload JobUpdateData.
                The job change is only valid if :
                * the job is not in the DONE run status.
                * the job changes from RUNNING to DONE run status and the job exit status is set

                The following changes are applied to the job :
                * if the run status is PENDING, when the run status is changed to RUNNING, the the started date is
                setted
                * if run status is RUNNING, when the run status is changed to DONE, then the finished date is setted

            responses:
                200:
                    description: the job update was successful
                    body: Job
                400:
                    description: request is not acceptable. Code ILLEGAL_JOB_CHANGE.
                    body: Error
                404:
                    description: no job found with the given jobId. Code JOB_NOT_FOUND.
                    body: Error
                500:
                    description: UNEXPECTED_ERROR.
                    body: Error
