#%RAML 1.0
title: Poomjobs API
version: v1
baseUri: https://api.codingmatters.org/poomjobs
mediaType: application/json

/jobs:
    displayName: JobCollection
    get:
        queryParameters:
            range: string
        responses:
            200:
                description: complete list of jobs or last elements of the list of jobs
                headers:
                    Content-Range: string
                    Accept-Range: string
                body: Job[]
    post:
        headers:
            account-id: string
        body: JobCreationData
        description: |
          A job is created from the minimal information provided with
          the payload JobCreationData.
          * The created job will have it's submission date setted.
          * The job accounting information will be initialized given the account-id header.
          * The job will have its run status setted to PENDING.
        responses:
            201:
                description: new job created
                headers:
                    Location: string
            400:
                description: request is not acceptable. Code ILLEGAL_JOB_SPEC.
                body: Error
            500:
                description: UNEXPECTED_ERROR.
                body: Error
    /{jobId}:
        displayName: JobResource
        uriParameters:
            jobId:
                type: string
                required: true
        get:
            description: |
                If a job with the given jobId, returns the full description of the job.
            responses:
                200:
                    description: a job with the given jobId is found and returned
                    body: Job
                404:
                    description: no job found with the given jobId. Code JOB_NOT_FOUND.
                    body: Error
                500:
                    description: UNEXPECTED_ERROR.
                    body: Error
        put:
            body: JobUpdateData
            headers:
                account-id: string
                current-version: string
            description: |
                The job with the given jobId is updated provided the payload JobUpdateData.
                The job change is only valid if :
                * the job is not in the DONE run status.
                * the job changes from RUNNING to DONE run status and the job exit status is set

                The following changes are applied to the job :
                * if the run status is PENDING, when the run status is changed to RUNNING, the the started date is
                setted
                * if run status is RUNNING, when the run status is changed to DONE, then the finished date is setted

            responses:
                200:
                    description: the job update was successful
                    body: Job
                400:
                    description: request is not acceptable. Code ILLEGAL_JOB_CHANGE.
                    body: Error
                404:
                    description: no job found with the given jobId. Code JOB_NOT_FOUND.
                    body: Error
                500:
                    description: UNEXPECTED_ERROR.
                    body: Error

types:
    Job:
        type: object
        properties:
            id: string
            version: string

            category: string
            name: string

            arguments:
                type: array
                items: string
            result: string

            accounting:
                type: object
                properties:
                    accountId: string

            status:
                type: object
                properties:
                    run:
                        enum: [PENDING, RUNNING, DONE]
                    exit:
                        enum: [SUCCESS, FAILURE]

            processing:
                type: object
                properties:
                    submitted: datetime-only
                    started: datetime-only
                    finished: datetime-only

    JobCreationData:
        type: object
        properties:

            category: string
            name: string

            arguments:
                type: array
                items: string

    JobUpdateData:
        type: object
        properties:
            result: string

            status:
                type: object
                properties:
                    run:
                        enum: [RUNNING, DONE]
                    exit:
                        enum: [SUCCESS, FAILURE]

    Error:
        type: object
        properties:
            token: string
            code:
                enum: [JOB_NOT_FOUND, UNEXPECTED_ERROR, ILLEGAL_JOB_CHANGE, ILLEGAL_JOB_SPEC]
            description: string