Job:
    type: object
    properties:
        id: string
        version: string

        category: string
        name: string

        arguments:
            type: array
            items: string
        result: string

        accounting:
            type: object
            properties:
                accountId: string

        status:
            type: object
            properties:
                run:
                    enum: [PENDING, RUNNING, DONE]
                exit:
                    enum: [SUCCESS, FAILURE]

        processing:
            type: object
            properties:
                submitted: datetime-only
                started: datetime-only
                finished: datetime-only

JobCreationData:
    type: object
    properties:

        category: string
        name: string

        arguments:
            type: array
            items: string

JobUpdateData:
    type: object
    properties:
        result: string

        status:
            type: object
            properties:
                run:
                    enum: [RUNNING, DONE]
                exit:
                    enum: [SUCCESS, FAILURE]

Runner:
    type: object
    properties:
        id: string
        callback: string
        competencies:
            type: object
            properties:
                categories:
                    type: array
                    items: string
                names:
                    type: array
                    items: string
        ttl: integer
        runtime:
            type: object
            properties:
                status:
                    enum: [IDLE, RUNNING, DISCONNECTED]
                created: datetime-only
                last-ping: datetime-only
RunnerData:
    type: object
    properties:
        callback: string
        ttl: integer
        competencies:
            type: object
            properties:
                categories:
                    type: array
                    items: string
                names:
                    type: array
                    items: string
RunnerStatusData:
    type: object
    properties:
        status:
          enum: [IDLE, RUNNING, DISCONNECTED]

Error:
    type: object
    properties:
        token: string
        code:
            enum: [JOB_NOT_FOUND, ILLEGAL_JOB_CHANGE, ILLEGAL_JOB_SPEC,
                RUNNER_NOT_FOUND, ILLEGAL_RUNNER_SPEC, ILLEGAL_RUNNER_CHANGE, ILLEGAL_RUNNER_STATUS_CHANGE,
                ILLEGAL_RANGE_SPEC, UNEXPECTED_ERROR,
                RUNNER_IS_BUSY,
                RESOURCE_NOT_FOUND]
        description: string